import { inject, Injectable } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { environment } from '../../../../environments/environment';

@Injectable({ providedIn: 'root' })
export class MarkdownRendererService {
  private readonly sanitizer = inject(DomSanitizer);
  private readonly baseDocumentUrl = `${environment.apiUrl}stored_documents`;

  // ── PUBLIC API ─────────────────────────────────────────────────────────────

  /**
   * Convert a markdown string to a SafeHtml object ready for [innerHTML] binding.
   */
  toSafeHtml(markdown: string): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(this.toHtml(markdown));
  }

  /**
   * Convert a markdown string to a plain HTML string.
   */
  toHtml(markdown: string): string {
    let html = markdown.trim();

    // 1. Process image URLs (markdown + raw <img>)
    html = this.processImageUrls(html);

    // 2. Protect raw HTML block elements from newline processing
    const htmlBlocks: string[] = [];
    html = html.replace(/(<table[\s\S]*?<\/table>)/gi, (match) => {
      htmlBlocks.push(match);
      return `%%HTML_BLOCK_${htmlBlocks.length - 1}%%`;
    });

    // 3. Markdown headings
    html = html.replace(/^#### (.*$)/gim, '<h4>$1</h4>');
    html = html.replace(/^### (.*$)/gim,  '<h3>$1</h3>');
    html = html.replace(/^## (.*$)/gim,   '<h2>$1</h2>');
    html = html.replace(/^# (.*$)/gim,    '<h1>$1</h1>');

    // 4. Bold & italic
    html = html.replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>');
    html = html.replace(/\*(.*?)\*/gim,     '<em>$1</em>');

    // 5. Unordered lists
    html = html.replace(/^\s*[-*]\s+(.*$)/gim, '<li>$1</li>');
    html = html.replace(/(<li>[\s\S]*?<\/li>)(\s*(?!<li>))/g, '<ul>$1</ul>$2');

    // 6. Paragraph-aware newline conversion
    //    Split on blank lines → each chunk becomes a <p> (unless already HTML)
    const blocks = html.split(/\n{2,}/);
    html = blocks
      .map(block => {
        block = block.trim();
        if (!block) return '';
        if (/^%%HTML_BLOCK_\d+%%$/.test(block)) return block;
        if (/^<(h[1-6]|ul|ol|li|table|div|pre|blockquote)/i.test(block)) return block;
        // Single newlines within a paragraph → <br>
        return `<p>${block.replace(/\n/g, '<br>')}</p>`;
      })
      .join('\n');

    // 7. Restore & enhance table blocks
    htmlBlocks.forEach((block, i) => {
      html = html.replace(`%%HTML_BLOCK_${i}%%`, this.enhanceTables(block));
    });

    return `<div class="rendered-markdown-content">${html.trim()}</div>`;
  }

  /**
   * Build a full markdown document from a raw API response object.
   * Returns both the raw markdown string and its SafeHtml equivalent.
   */
  buildFromResponse(
    apiResponse: any,
    filteredResponse: any,
    documentFileName: string,
    selectedFileName?: string
  ): { raw: string; safe: SafeHtml } {
    const raw = this.extractMarkdown(apiResponse, filteredResponse);
    const safe = this.toSafeHtml(raw);
    return { raw, safe };
  }

  // ── PRIVATE HELPERS ────────────────────────────────────────────────────────

  private extractMarkdown(apiResponse: any, filteredResponse: any): string {
    if (!apiResponse) {
      return '# No data available\n\nPlease parse a document first.';
    }

    if (apiResponse.markdown)               return apiResponse.markdown;
    if (apiResponse.parsed_data?.markdown)  return apiResponse.parsed_data.markdown;
    if (apiResponse.data?.markdown)         return apiResponse.data.markdown;

    try {
      return this.generateMarkdownFromResponse(filteredResponse ?? apiResponse);
    } catch {
      return '# Error Generating Markdown\n\nThere was an error processing the document data.';
    }
  }

  private generateMarkdownFromResponse(response: any): string {
    let md = '# Document Analysis Results\n\n';

    if (response.table || response.SUBLET || response.MercedesBenz) {
      md += this.fromUsageStructure(response);
    } else if (response.image) {
      md += this.fromNewStructure(response);
    } else {
      md += this.fromGenericStructure(response);
    }

    md += '---\n';
    md += `*Generated by GDocz AI on ${new Date().toLocaleDateString()}*`;
    return md;
  }

  private fromUsageStructure(response: any): string {
    let md = '## Extracted Document Data\n\n';

    if (response.table && Array.isArray(response.table)) {
      md += '### Tables\n\n';
      response.table.forEach((table: any, i: number) => {
        md += `**Table ${i + 1}:**\n\n`;
        md += table.rows && table.headers
          ? this.markdownTable(table)
          : '- ' + (table.row?.join(', ') ?? '') + '\n';
        md += '\n';
      });
    }

    if (response.SUBLET) {
      md += '### SUBLET Information\n\n';
      md += this.objectToList(response.SUBLET) + '\n';
    }

    if (response.MercedesBenz) {
      md += '### Mercedes Benz Information\n\n';
      const mb = response.MercedesBenz;

      if (mb.PARTS?.table) {
        md += '#### Parts\n\n';
        mb.PARTS.table.forEach((p: any, i: number) => {
          md += `**Part ${i + 1}:**\n` + this.objectToList(p) + '\n';
        });
      }

      if (mb.LABOUR?.table) {
        md += '#### Labour\n\n';
        mb.LABOUR.table.forEach((l: any, i: number) => {
          md += `**Labour ${i + 1}:**\n` + this.objectToList(l) + '\n';
        });
      }

      const companyKey = Object.keys(mb).find(k => k !== 'PARTS' && k !== 'LABOUR');
      if (companyKey) {
        md += '#### Company Details\n\n' + this.objectToList(mb[companyKey]);
      }
    }

    return md;
  }

  private fromNewStructure(response: any): string {
    let md = '## Document Analysis\n\n### Extracted Image Data\n\n';

    md += typeof response.image === 'string'
      ? `![Extracted Image](${response.image})\n\n`
      : `- **Image**: ${response.image}\n\n`;

    const others = Object.keys(response).filter(k => k !== 'image');
    if (others.length) {
      md += '### Additional Data\n\n';
      others.forEach(k => { md += `- **${this.formatKey(k)}**: ${response[k]}\n`; });
    }

    return md;
  }

  private fromGenericStructure(response: any): string {
    let md = '';

    if (response.metadata) {
      md += '## Processing Metadata\n\n' + this.objectToList(response.metadata) + '\n';
    }
    if (response.document) {
      md += '## Document Information\n\n' + this.objectToList(response.document) + '\n';
    }
    if (response.content) {
      md += '## Document Content\n\n' + this.processContent(response.content);
    }
    if (response.extracted_data) {
      md += '## Extracted Data\n\n' + this.objectToList(response.extracted_data) + '\n';
    }

    return md;
  }

  private processContent(content: any): string {
    let md = '';

    if (Array.isArray(content)) {
      content.forEach((item: any, i: number) => {
        md += `### ${item.page ? `Page ${item.page}` : `Section ${i + 1}`}\n\n`;
        if (item.text) md += `${item.text}\n\n`;

        if (item.blocks?.length) {
          md += '**Extracted Blocks:**\n\n';
          item.blocks.forEach((b: any) => {
            if (b.type && b.text) md += `- **${b.type}**: ${b.text}\n`;
          });
          md += '\n';
        }

        if (item.tables?.length) {
          md += '**Tables:**\n\n';
          item.tables.forEach((t: any, ti: number) => {
            md += `**Table ${ti + 1}:**\n\n` + this.markdownTable(t) + '\n';
          });
        }
      });
    } else if (typeof content === 'string') {
      md += `${content}\n\n`;
    } else if (typeof content === 'object') {
      md += this.objectToList(content);
    }

    return md;
  }

  private objectToList(obj: any, indent = 0): string {
    let md = '';
    const pad = '  '.repeat(indent);

    Object.keys(obj).forEach(key => {
      const val = obj[key];
      if (val == null) return;

      if (Array.isArray(val)) {
        if (!val.length) {
          md += `${pad}- **${this.formatKey(key)}**: []\n`;
        } else if (typeof val[0] === 'object') {
          md += `${pad}- **${this.formatKey(key)}**:\n`;
          val.forEach((item, i) => {
            md += `${pad}  ${i + 1}.\n` + this.objectToList(item, indent + 2);
          });
        } else {
          md += `${pad}- **${this.formatKey(key)}**: ${val.join(', ')}\n`;
        }
      } else if (typeof val === 'object') {
        md += `${pad}- **${this.formatKey(key)}**:\n` + this.objectToList(val, indent + 1);
      } else {
        md += `${pad}- **${this.formatKey(key)}**: ${val}\n`;
      }
    });

    return md;
  }

  private markdownTable(table: any): string {
    if (!table.headers || !table.rows) return 'Invalid table data\n';

    let md = '| ' + table.headers.join(' | ') + ' |\n';
    md    += '|' + table.headers.map(() => '---').join('|') + '|\n';
    table.rows.forEach((row: any[]) => { md += '| ' + row.join(' | ') + ' |\n'; });
    return md + '\n';
  }

  private processImageUrls(html: string): string {
    // Markdown image syntax → <img>
    html = html.replace(/!\[(.*?)\]\((.*?)\)/g, (_, alt, src) => {
      const url = this.resolveUrl(src);
      return `<div class="image-container"><img src="${url}" alt="${alt}" class="markdown-image" /></div>`;
    });

    // Raw <img src="..."> with relative paths
    html = html.replace(/<img([^>]+)src="([^">]+)"([^>]*)>/g, (match, pre, src, post) => {
      if (/^https?:|^data:/.test(src)) return match;
      return `<img${pre}src="${this.resolveUrl(src)}"${post}>`;
    });

    return html;
  }

  private resolveUrl(path: string): string {
    if (/^https?:|^data:/.test(path)) return path;
    return path.startsWith('/')
      ? `${this.baseDocumentUrl}${path}`
      : `${this.baseDocumentUrl}/${path}`;
  }

  private enhanceTables(html: string): string {
    // Strip stray <br> immediately around structural table tags
    const structural = 'table|thead|tbody|tfoot|tr';

    html = html.replace(/(?:<br\s*\/?>|\s)*<table/gim, '<table');
    html = html.replace(/<\/table>(?:<br\s*\/?>|\s)*/gim, '</table>');

    html = html.replace(new RegExp(`(<(${structural})[^>]*>)(?:\\s|<br\\s*\\/?>)+`, 'gim'), '$1');
    html = html.replace(new RegExp(`(?:\\s|<br\\s*\\/?>)+(<\\/(${structural})>)`, 'gim'), '$1');
    html = html.replace(
      new RegExp(`(<\\/(${structural})>)(?:\\s|<br\\s*\\/?>)+(<(${structural})|$)`, 'gim'),
      '$1$3'
    );

    // Bootstrap classes
    html = html.replace(/<table>/g,  '<table class="table table-bordered table-sm">');
    html = html.replace(/<td>/g,     '<td class="p-2">');
    html = html.replace(/<th>/g,     '<th class="p-2 bg-light">');

    // Responsive wrapper
    html = html.replace(/<table/g,    '<div class="table-responsive"><table');
    html = html.replace(/<\/table>/g, '</table></div>');

    // Clean up any breaks that crept in beside the wrapper
    html = html.replace(/(<div class="table-responsive">)(?:\s|<br\s*\/?>)+/gim, '$1');
    html = html.replace(/(?:\s|<br\s*\/?>)+(<\/div>)/gim, '$1');

    return html;
  }

  // ── SHARED UTILITIES (also used by components directly) ───────────────────

  formatKey(key: string): string {
    return key
      .replace(/([A-Z])/g, ' $1')
      .replace(/_/g, ' ')
      .replace(/^./, s => s.toUpperCase())
      .trim();
  }
}