# -*- coding: utf-8 -*-
"""
Sundarams NetSuite Vendor Master Mapping Table
Auto-generated from OCR VENDOR LIST.xlsx
"""

from typing import Dict

VENDOR_MASTER: Dict[str, Dict[str, str]] = {
    "A V ELECTRICALS": {
        "entity":            "1590652254",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "928",
        "custcol_subledger": "373",
    },
    "AD EXP ENTERPRISE": {
        "entity":            "1680650008",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "AUDATEX SOLUTIONS PVT LTD": {
        "entity":            "1590652104",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "928",
        "custcol_subledger": "373",
    },
    "AWP ASSISTANCE (INDIA) PRIVATE LIMITED": {
        "entity":            "1590652189",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "656",
        "custcol_subledger": "397",
    },
    "BERRY N BLOSSOM THE PASTRY LAND PVT LTD": {
        "entity":            "1600652001",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "BHARANI ENTERPRISES": {
        "entity":            "1590652445",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "BHARTI AIRTEL LIMITED": {
        "entity":            "1590652146",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "664",
        "custcol_subledger": "587",
    },
    "BODYCOAT INDIA PRIVATE LIMITED": {
        "entity":            "1590652465",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "611",
        "custcol_subledger": "1305",
    },
    "BODYCOAT INDIA PRIVATE LIMITED": {
        "entity":            "1590652465",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "611",
        "custcol_subledger": "1305",
    },
    "BODYCOAT INDIA PRIVATE LIMITED": {
        "entity":            "1590652465",
        "department":        "2",
        "location":          "365",
        "sm_location":       "167",
        "account":           "611",
        "custcol_subledger": "1305",
    },
    "BRAND MAGNETIC SOLUTION": {
        "entity":            "1600652262",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "BRAND MAGNETIC SOLUTION": {
        "entity":            "1600652262",
        "department":        "2",
        "location":          "627",
        "sm_location":       "168",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "BRIO HOSPITALITY PRIVATE LIMITED": {
        "entity":            "1600652202",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "CARTRADE TECH LIMITED": {
        "entity":            "1670650007",
        "department":        "2",
        "location":          "365",
        "sm_location":       "167",
        "account":           "666",
        "custcol_subledger": "488",
    },
    "CHENNAI AUTO ANCILLARY INDUSTIRAL INFRASTRUCTURE UPGRADATION COMPANY": {
        "entity":            "1590652062",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "931",
        "custcol_subledger": "525",
    },
    "CHITTAL PAPER COMPANY": {
        "entity":            "1590652041",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "943",
        "custcol_subledger": "583",
    },
    "CHITTAL PAPER COMPANY": {
        "entity":            "1590652041",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "943",
        "custcol_subledger": "583",
    },
    "CHRIS MERCHANT PRIVATE LIMITED": {
        "entity":            "1590652466",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "CLOUD DESIGNS PRIVATE LIMITED": {
        "entity":            "1600652170",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "CONTINENTAL INDIA PRIVATE LIMITED": {
        "entity":            "1590652468",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "EECONVENTIA PRIVATE LIMITED": {
        "entity":            "1600652303",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "EXICOM TELE SYSTEMS LIMITED": {
        "entity":            "1590659017",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "928",
        "custcol_subledger": "373",
    },
    "FARAH ENTERPRISES": {
        "entity":            "1590652169",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "GOOD LUCK FLORIST": {
        "entity":            "1600652073",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "HARD SOFT INFOSYS": {
        "entity":            "1590652253",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "943",
        "custcol_subledger": "583",
    },
    "HARD SOFT INFOSYS": {
        "entity":            "1590652253",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "943",
        "custcol_subledger": "583",
    },
    "HIMANSU AGENCIES": {
        "entity":            "1590652071",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "931",
        "custcol_subledger": "521",
    },
    "HIMANSU AGENCIES": {
        "entity":            "1590652071",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "931",
        "custcol_subledger": "521",
    },
    "JAGAN S (NILAA ARTS)": {
        "entity":            "1600652138",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "KANNAN AYYAMPERUMAL": {
        "entity":            "1590652413",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "KANNAN AYYAMPERUMAL": {
        "entity":            "1590652413",
        "department":        "2",
        "location":          "627",
        "sm_location":       "168",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "KARTHIKEYAN R": {
        "entity":            "1600652210",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "KUMAR V": {
        "entity":            "1590652331",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "943",
        "custcol_subledger": "583",
    },
    "KUMAR V": {
        "entity":            "1590652331",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "943",
        "custcol_subledger": "583",
    },
    "KUMAR V": {
        "entity":            "1590652331",
        "department":        "2",
        "location":          "365",
        "sm_location":       "167",
        "account":           "943",
        "custcol_subledger": "583",
    },
    "M PRODUCTIONS": {
        "entity":            "1600652292",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "M/S SMART AUTO SOLUTIONS": {
        "entity":            "1590652307",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "928",
        "custcol_subledger": "373",
    },
    "MALINI ABLUDU RAMESH": {
        "entity":            "1680650005",
        "department":        "2",
        "location":          "627",
        "sm_location":       "168",
        "account":           "643",
        "custcol_subledger": "422",
    },
    "MANOHAR S": {
        "entity":            "1590652225",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "643",
        "custcol_subledger": "422",
    },
    "MARUTI MOTO CORP": {
        "entity":            "1590621426",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "MILLIVISIONS MARKETING PVT  LTD": {
        "entity":            "1590621451",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "MRS.SWETHA    SUNDEEP ANAND (DEPOSITS OTHERS-MB CHENN": {
        "entity":            "1592910003",
        "department":        "2",
        "location":          "627",
        "sm_location":       "168",
        "account":           "643",
        "custcol_subledger": "422",
    },
    "NANOVIV TECHNOLOGIES INDIA PRIVATE LIMITED": {
        "entity":            "1590652402",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "611",
        "custcol_subledger": "1305",
    },
    "NATIONAL INDUSTRIAL SECURITY AGENCY": {
        "entity":            "1590652019",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "940",
        "custcol_subledger": "347",
    },
    "NATIONAL INDUSTRIAL SECURITY AGENCY": {
        "entity":            "1590652019",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "940",
        "custcol_subledger": "347",
    },
    "NATIONAL TEXTILE WASTE CORPORATION": {
        "entity":            "1590621453",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "NATURAL OFFICE MART": {
        "entity":            "1590652042",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "931",
        "custcol_subledger": "521",
    },
    "NATURAL OFFICE MART": {
        "entity":            "1590652042",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "931",
        "custcol_subledger": "521",
    },
    "NETTYFISH SOLUTIONS PRIVATE LIMITED": {
        "entity":            "1600652259",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "NREACH ONLINE SERVICES PRIVATE LIMITED": {
        "entity":            "1600652161",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "907",
        "custcol_subledger": "1311",
    },
    "ONE TOUCH ENTERPRISES": {
        "entity":            "1600652134",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "488",
    },
    "PERFORMANCE TYRES": {
        "entity":            "1590621452",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "PERFORMAX SPORTS & LIVE": {
        "entity":            "1600652077",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "POPULAR MARUTHI PAINTS": {
        "entity":            "1590652366",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "PREMIUM TYRE SOLUTION": {
        "entity":            "1590621443",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "PRIMUS EVENTS & EXHIBITIONS": {
        "entity":            "1600652199",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "QUANTRON BUSINESS TECH SOLUTION PRIVATE LIMITED": {
        "entity":            "1590652223",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "611",
        "custcol_subledger": "1305",
    },
    "RADTECH SYSTEMS PRIVATE LIMITED": {
        "entity":            "1590652135",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "940",
        "custcol_subledger": "367",
    },
    "RADTECH SYSTEMS PRIVATE LIMITED": {
        "entity":            "1590652135",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "940",
        "custcol_subledger": "367",
    },
    "RADTECH SYSTEMS PRIVATE LIMITED": {
        "entity":            "1590652135",
        "department":        "2",
        "location":          "627",
        "sm_location":       "168",
        "account":           "940",
        "custcol_subledger": "367",
    },
    "REINHOLD WUERTH INDIA PVT LTD": {
        "entity":            "1590621428",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "871",
        "custcol_subledger": "1201",
    },
    "ROHITH SRINIVASAN": {
        "entity":            "1600652152",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "ROHITH SRINIVASAN": {
        "entity":            "1600652152",
        "department":        "2",
        "location":          "627",
        "sm_location":       "168",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "S D S ASSOCIATES": {
        "entity":            "1600652159",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "394",
    },
    "SAI BABA BUSINESS SOLUTIONS PVT LTD": {
        "entity":            "1590652076",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SAI BABA BUSINESS SOLUTIONS PVT LTD": {
        "entity":            "1590652076",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SAKTHI MANAGEMENT SERVICES": {
        "entity":            "1590652316",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "940",
        "custcol_subledger": "345",
    },
    "SATHISH PRINTS": {
        "entity":            "1590659013",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SATHISH PRINTS": {
        "entity":            "1590659013",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SATHRI MANAGEMENT SERVICES": {
        "entity":            "1590652069",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "931",
        "custcol_subledger": "525",
    },
    "SATHRI MANAGEMENT SERVICES": {
        "entity":            "1590652069",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "931",
        "custcol_subledger": "525",
    },
    "SATHRI MANAGEMENT SERVICES": {
        "entity":            "1590652069",
        "department":        "2",
        "location":          "627",
        "sm_location":       "168",
        "account":           "931",
        "custcol_subledger": "525",
    },
    "SHARP BUSINESS SYSTEMS": {
        "entity":            "1590652426",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SHARP BUSINESS SYSTEMS": {
        "entity":            "1590652426",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SHEELPE ENTERPRISE PVT LTD": {
        "entity":            "1590652359",
        "department":        "2",
        "location":          "354/355",
        "sm_location":       "159/160",
        "account":           "666",
        "custcol_subledger": "484",
    },
    "SHEELPE ENTERPRISE PVT LTD": {
        "entity":            "1590652359",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "666",
        "custcol_subledger": "484",
    },
    "SHERATON GRAND CHENNAI RESORT & SPA": {
        "entity":            "1600652162",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "1201",
    },
    "SHRI SECURITY SERVICES": {
        "entity":            "1600652284",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "940",
        "custcol_subledger": "1302",
    },
    "SKOVIAN VENTURES": {
        "entity":            "1600652283",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "SOMETHING NEW AROUND": {
        "entity":            "1600652002",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "SPEED EX": {
        "entity":            "1600652030",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "394",
    },
    "SRI ANNAI STICKERS": {
        "entity":            "1600652145",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SRI ANNAI STICKERS": {
        "entity":            "1600652145",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "SSM FLOWER STALL": {
        "entity":            "1600652242",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "SUNDHARAMS PRIVATE LIMITED": {
        "entity":            "1600652109",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "392",
    },
    "THE GRAND SAROVAR INN AND SUITES": {
        "entity":            "1590652398",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "661",
        "custcol_subledger": "577",
    },
    "UGAOO AGRITECH PRIVATE LIMITED": {
        "entity":            "1600652178",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "654",
        "custcol_subledger": "393",
    },
    "VEDHA ENTERPRISES": {
        "entity":            "1590652373",
        "department":        "2",
        "location":          "354",
        "sm_location":       "159",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "VEDHA ENTERPRISES": {
        "entity":            "1590652373",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "941",
        "custcol_subledger": "579",
    },
    "WANNAMO MARKETING PRIVATE LIMITED": {
        "entity":            "1600652155",
        "department":        "2",
        "location":          "355",
        "sm_location":       "160",
        "account":           "666",
        "custcol_subledger": "479",
    },
    "ZOHO CORPORATION PRIVATE LIMITED": {
        "entity":            "1590652421",
        "department":        "5",
        "location":          "354",
        "sm_location":       "159",
        "account":           "928",
        "custcol_subledger": "376",
    },
}
